# Generated by Django 4.2.29 on 2026-04-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseStripeSubscription',
        ),
    ]
