HTK_ASSESSMENTS_ASSESSMENT_MODEL = 'htk.Assessment'
HTK_ASSESSMENTS_QUESTION_MODEL = 'htk.Question'
HTK_ASSESSMENTS_QUESTION_CHOICE_MODEL = 'htk.QuestionChoice'
HTK_ASSESSMENTS_ANSWER_MODEL = 'htk.Answer'
